/**
 * Schema writer — generates TypeScript source code for a FormSchema file
 * from a set of field mappings.
 */

import { FieldType } from '../types';

export interface FieldMapping {
  pdfFieldName: string;
  id: string;
  type: FieldType;
  label: string;
  required: boolean;
  format?: string;
  min?: number;
  max?: number;
  allowedValues?: string[];
}

export interface SchemaConfig {
  formCode: string;
  taxYear: number;
  irsRevision: string;
  name: string;
  fields: FieldMapping[];
}

/**
 * Generate a complete TypeScript source string for a FormSchema file.
 * The output is valid TS that can be saved to `schemas/{formCode}-{taxYear}.ts`.
 */
export function generateSchemaSource(config: SchemaConfig): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${config.name}`);
  lines.push(` * Form ${config.formCode} — Tax Year ${config.taxYear}`);
  lines.push(` * IRS Revision: ${config.irsRevision}`);
  lines.push(` * Generated by schema-writer`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import type { FormSchema } from '../types/schema-types';`);
  lines.push(`import { FieldType } from '../types/field-types';`);
  lines.push(``);

  const varName = `${config.formCode.toLowerCase().replace(/[^a-z0-9]/g, '_')}_${config.taxYear}`;

  lines.push(`export const ${varName}: FormSchema = {`);
  lines.push(`  formCode: ${JSON.stringify(config.formCode)},`);
  lines.push(`  taxYear: ${config.taxYear},`);
  lines.push(`  irsRevision: ${JSON.stringify(config.irsRevision)},`);
  lines.push(`  name: ${JSON.stringify(config.name)},`);
  lines.push(`  fields: [`);

  for (const field of config.fields) {
    lines.push(`    {`);
    lines.push(`      id: ${JSON.stringify(field.id)},`);
    lines.push(`      pdfFieldName: ${JSON.stringify(field.pdfFieldName)},`);
    lines.push(`      label: ${JSON.stringify(field.label)},`);
    lines.push(`      type: ${fieldTypeToEnum(field.type)},`);
    if (field.required) {
      lines.push(`      required: true,`);
    }
    if (field.format) {
      lines.push(`      format: ${JSON.stringify(field.format)},`);
    }
    if (field.min !== undefined) {
      lines.push(`      min: ${field.min},`);
    }
    if (field.max !== undefined) {
      lines.push(`      max: ${field.max},`);
    }
    if (field.allowedValues && field.allowedValues.length > 0) {
      lines.push(`      allowedValues: [${field.allowedValues.map((v) => JSON.stringify(v)).join(', ')}],`);
    }
    lines.push(`    },`);
  }

  lines.push(`  ],`);
  lines.push(`};`);
  lines.push(``);

  return lines.join('\n');
}

function fieldTypeToEnum(type: FieldType): string {
  const map: Record<FieldType, string> = {
    [FieldType.Text]: 'FieldType.Text',
    [FieldType.Checkbox]: 'FieldType.Checkbox',
    [FieldType.Radio]: 'FieldType.Radio',
    [FieldType.Dropdown]: 'FieldType.Dropdown',
    [FieldType.SSN]: 'FieldType.SSN',
    [FieldType.EIN]: 'FieldType.EIN',
    [FieldType.Date]: 'FieldType.Date',
    [FieldType.Currency]: 'FieldType.Currency',
    [FieldType.Percentage]: 'FieldType.Percentage',
    [FieldType.Integer]: 'FieldType.Integer',
    [FieldType.ZipCode]: 'FieldType.ZipCode',
    [FieldType.Phone]: 'FieldType.Phone',
  };
  return map[type] ?? 'FieldType.Text';
}
